source("~/labo/src/lib/exp_lib.r")
# corrida completa
# exp_start( "8121TSb",  deletevm= FALSE)
# exp_start( "8121HTb",  deletevm= FALSE)
# exp_start( "8121ZZb")
# Corrida completa
# exp_start( "8121TSc",  deletevm= FALSE)
# exp_start( "8121HTc",  deletevm= FALSE)
# exp_start( "8121ZZc")
# exp_start( "8122FEa",  deletevm= FALSE)
# exp_start( "8122TSa",  deletevm= FALSE)
# exp_start( "8122HTa",  deletevm= FALSE)
# exp_start( "8122ZZa")
# exp_start( "8122TSb",  deletevm= FALSE)
# exp_start( "8122HTb",  deletevm= FALSE)
# exp_start( "8122ZZb",  deletevm= FALSE)
# exp_start( "8131HBd")
# exp_start( "8122TSc",  deletevm= FALSE)
# exp_start( "8122HTc",  deletevm= FALSE)
# exp_start( "8122ZZc",  deletevm= FALSE)
# exp_start( "8131HBd")
# exp_start( "8122TSd",  deletevm= FALSE)
# exp_start( "8122HTd",  deletevm= FALSE)
# exp_start( "8122ZZd",  deletevm= FALSE)
# exp_start( "8131HBe")
# exp_start( "8122HTe",  deletevm= FALSE)
# exp_start( "8122ZZe",  deletevm= FALSE)
# exp_start( "8122TSf",  deletevm= FALSE)
# exp_start( "8122HTf",  deletevm= FALSE)
# exp_start( "8122ZZf",  deletevm= FALSE)
# exp_start( "8122TSg",  deletevm= FALSE)
# exp_start( "8122HTg",  deletevm= FALSE)
# exp_start( "8122ZZg",  deletevm= FALSE)
# exp_start( "8131HBf")
# exp_start( "8122HTh",  deletevm= FALSE)
# exp_start( "8122ZZh",  deletevm= FALSE)
# exp_start( "8131HBg")
# exp_start( "termonuclear-FEa",  deletevm= FALSE)
# exp_start( "termonuclear-TSa",  deletevm= FALSE)
# exp_start( "termonuclear-HTa",  deletevm= FALSE)
# exp_start( "termonuclear-ZZa",  deletevm= FALSE)
exp_start( "8122TSi",  deletevm= FALSE)
exp_start( "8122HTi",  deletevm= FALSE)
exp_start( "8122ZZi")



