---
title: 'EDA & Tests'
author: "Claudio Sebastián Castillo"
date: "`r format(Sys.Date(), '%d de %B de %Y') `"
output:
  pdf_document: 
    number_sections: true
    toc: true 
    toc_depth: 3  
linestretch: 1
params:
  AnalisisIntegrador: no
  EDA: no
  ANOVA: no
  values:
    label: Variable numerica
    input: text
    value: ''
  categories:
    label: Variable categorica o factor
    input: text
    value: ''
  ctranformacion: no
  ANOVA_multivar: no
  categorieANOVAm:
    label: Variable categorica o factor
    input: text
    value: ''
  LDA: no
  categoriesLDA:
    label: 'LDA: Variable categorica o factor'
    input: text
    value: ''
  valores_lda_nvaobs:
    label: Valores de la nueva observaciones a clasificar
    input: text
    value: ''
  QDA: no
  categoriesQDA:
    label: 'QDA: Variable categorica o factor'
    input: text
    value: ''
  valores_qda_nvaobs:
    label: Valores de la nueva observaciones a clasificar
    input: text
    value: ''
  Regresion_Logistica: no
  categoriesLR:
    label: 'RL Variable categorica o factor'
    input: text
    value: ''
  SVM: no
  categoriesSVM:
    label: 'SVM: Variable categorica o factor'
    input: text
    value: ''
  valores_SVM_nvaobs:
    label: Valores de la nueva observaciones a clasificar
    input: text
    value: ''
  Clustering: no
  PCA: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, comment=NA )
knitr::opts_chunk$set(fig.align = 'center')
source("Unidad0_repos_and_tools.R")
```

```{r, params}
AI = params$AnalisisIntegrador
EDA = params$EDA
ANOVA = params$ANOVA
variable_numerica = params$values
variable_factor = params$categories
ctranformacion = params$ctranformacion
options(scipen = 999) # inhabilito notacion científica
ANOVAm = params$ANOVA_multivar
variable_factor_anovam = params$categorieANOVAm
LDA = params$LDA
variable_factor_lda = params$categoriesLDA
if (params$valores_lda_nvaobs == ''){
  valores_lda_nvaobs <- NA
} else {
 valores_lda_nvaobs =  unlist(stringr::str_split(params$valores_lda_nvaobs, ","))
}
QDA = params$QDA
variable_factor_qda = params$categoriesQDA
if (params$valores_qda_nvaobs == ''){
  valores_qda_nvaobs <- NA
} else {
 valores_qda_nvaobs =  unlist(stringr::str_split(params$valores_qda_nvaobs, ","))
}
SVM = params$SVM
variable_factor_svm = params$categoriesSVM
Clustering = params$Clustering
Regresion_Logistica = params$Regresion_Logistica
variable_factor_lr = params$categoriesLR
PCA = params$PCA
```

```{r, tools}
multieda <- function(list, df = 1){
  
  lista_resultados <- list()
  
  # CV = proporcion que representa el desvıo estandar de la media aritmetica
  lista_resultados$coeficiente_variacion <- list[[df]] %>% 
    dplyr::select_if(is.numeric) %>% 
    summarise_all(raster::cv, na.rm =T) 
  
  lista_resultados$sesgo <- list[[df]] %>% 
    dplyr::select_if(is.numeric) %>% 
    summarise_all(moments::skewness) 
  
  # Las distribuciones leptocurticas tienen coeficientes superiores a 3 y las
  # platicurticas coeficientes menores a 3
  
  lista_resultados$curtosis <- list[[df]] %>% 
    dplyr::select_if(is.numeric) %>% 
    summarise_all(moments::kurtosis)
  
  # Estadística Robusta
  
  # Median Absolute Deviation= mediana de los desvıos absolutos respecto de la mediana
  lista_resultados$mad <- list[[df]] %>% 
    dplyr::select_if(is.numeric) %>% 
    summarise_all(mad)
  
  # grafico de correlacion
  # lista_resultados$m_correlacion <- list[[df]] %>%
  #   select_if(is.numeric) %>% 
  #   cor(., use="complete.obs") %>% 
  #   round(., 2) 
  
  lista_resultados
}

# Outlier detection
# iris %>%
#   rstatix::identify_outliers('Sepal.Width')

```

# EDA

```{r, eval= (EDA | AI)}
eda_list <- list()
eda_list$df <- fread("~/R/labo/datasets/paquete_premium_202011.csv", stringsAsFactors= TRUE)
dataset = 1
#results = multieda(eda_list, dataset)
```

```{r}
# ver diccionario datos
```

### structure

```{r, eval=EDA}
str(eda_list[[dataset]])
```

### Summary

```{r, eval=EDA}
summary(eda_list[[dataset]]) #%>% 
  # kable() %>% 
  # kable_styling(full_width = F, font_size = 9) %>% 
  # row_spec(0, angle = 90)
```

<!-- ### Distribución de datos -->

<!-- ```{r, eval=EDA, fig.align='center'} -->
<!-- knit_print(results) -->
<!-- ``` -->

<!-- Las medianas se encuentran cerca de las medias? Si es así podemos pensar que no hay outliers evaluando cada variable por separado, a no ser que haya enmascaramiento. Ver outliers multivariados. -->

### Analiso los tipos de clientes

```{r}
table(eda_list$df$clase_ternaria)
```

```{r}
df_numeric = eda_list$df %>% select_if(is.numeric)
df_numeric = as_tibble(df_numeric)
```

```{r}
nas = df_numeric %>%  dplyr::select(everything()) %>%  # replace to your needs
  summarise_all(funs(sum(is.na(.)))) %>% t() 
  
nas = tibble(var = rownames(nas), nas = nas[, 1]) %>% filter(nas > 0) %>% arrange(desc(nas))
nas %>% kable()
```

<!-- Campos y Grupos -->

<!-- - datos del cliente: cliente_antiguedad, cliente_edad,   -->

<!-- - rentabilidad cliente:  mrentabilidad, mrentabilidad_annua, mcomisiones, mactivos_margen, mpasivos_margen,  -->

<!-- - cantidad/monto de productos: cproductos, tcuentas, ccuenta_corriente y mcuenta_corriente, ccaja_ahorro y mcaja_ahorro, mcaja_ahorro_dolares, mdescubierto_preacordado, mcuentas_saldo (!), ctarjeta_debito, mautoservicio, ctarjeta_visa, ctarjeta_master, mtarjeta_master_consumo, cprestamos_personales,  mprestamos_personales, cprestamos_prendarios y mprestamos_prendarios, cprestamos_hipotecarios y mprestamos_hipotecarios, cinversion1 y minversion1_pesos, seguros (varios), ccaja_seguridad,  -->

<!-- - movimentos cliente: ctarjeta_debito_trx, ctarjeta_visa_trx, mtarjeta_visa_consumo, ctarjeta_master_trx, cprestamos_personales, cprestamos_prendarios, cprestamos_prendarios, cprestamos_hipotecarios, cplazo_fijo, cinversion1 y minversion1_pesos y cinversion2 y minversion2_pesos (!), cpayroll_trx y cpayroll2_trx (haberes), ccuenta_debitos_automaticos y mcuenta_debitos_automaticos,  ctarjeta_visa_debitos_automaticos/mtarjeta_visa_debitos_automaticos,  ctarjeta_master_debitos_automaticos/mttarjeta_master_debitos_automaticos, cpagodeservicios y mpagodeservicios,  -->

<!-- - acreditación de haberes: cpayroll_trx, mpayroll, mpayroll2 -->

<!-- - perfil uso: cpagomiscuentas y mpagomiscuentas,  -->


<!-- # quedé en variable 70 -->

<!-- Es probable que los baja+2 sean individuos con poco movimiento y pocos productos. O estaría vinculado a saldo negativos? -->

<!-- 1) ¿Qué características tienen los clientes vip? var:cliente_vip,   -->
<!-- 2) Ver correlación de grupo rentabilidad y cantidad de productos con clases ternarias,  -->
<!-- 3) Ver correlación de mcuenta_saldo (saldo total de todas las cuentas del cliente) y clase,  -->
<!-- 4) Ver correlación de grupo de movimientos cliente y clase,  -->
<!-- 5) Ver correlacion de grupo inversion y clase,  -->
<!-- 6) ver Acreditacion de haberes y clase -->

<!-- LIMPIEZA -->
<!-- - excluir: tpaquetes*, ccuenta_corriente -->

### Target, Variables y Relaciones

```{r}

var_fmovimientos = c("ctarjeta_debito_trx", "ctarjeta_visa_trx", "mtarjeta_visa_consumo", "ctarjeta_master_trx", "cprestamos_personales", "cprestamos_prendarios", "cprestamos_prendarios", "cprestamos_hipotecarios", "cplazo_fijo", "cinversion1", "minversion1_pesos", "cinversion2", "minversion2", "cpayroll_trx", "cpayroll2_trx",  "ccuenta_debitos_automaticos", "mcuenta_debitos_automaticos", "ctarjeta_visa_debitos_automaticos", "mtarjeta_visa_debitos_automaticos", "ctarjeta_master_debitos_automaticos", "mttarjeta_master_debitos_automaticos", "cpagodeservicios", "mpagodeservicios")


var_productos = c("cproductos", "tcuentas", "ccuenta_corriente", "mcuenta_corriente", "ccaja_ahorro", "mcaja_ahorro", "mcaja_ahorro_dolares", "mdescubierto_preacordado", "mcuentas_saldo", "ctarjeta_debito", "mautoservicio", "ctarjeta_visa", "ctarjeta_master", "mtarjeta_master_consumo", "cprestamos_personales",  "mprestamos_personales", "cprestamos_prendarios", "mprestamos_prendarios", "cprestamos_hipotecarios", "mprestamos_hipotecarios", "cinversion1", "minversion1_pesos", "cseguro_vida","cseguro_auto", "ccaja_seguridad")


var_target = eda_list$df %>% select(clase_ternaria) #%>% 
  # mutate(clase_ternaria = case_when(
  #   clase_ternaria == "CONTINUA"  ~ 1,
  #   clase_ternaria == 'BAJA+1' ~ -1,
  #   clase_ternaria == 'BAJA+2' ~ -2))

```

# Correlaciones?

```{r}

df_numeric_cor = df_numeric %>% 
  select(var_fmovimientos) %>% 
  bind_cols(var_target) %>% 
  cor(., use="complete.obs") %>%
  round(., 2)
  
corrplot(df_numeric_cor, type = "upper", tl.pos = "td",
         method = "circle", tl.cex = 0.5, tl.col = 'black',
         order = "hclust", diag = FALSE)
```


```{r}
df_numeric_cor = df_numeric %>% 
  select(var_productos) %>% 
  bind_cols(var_target) %>% 
  cor(., use="complete.obs") %>%
  round(., 2)
  
corrplot(df_numeric_cor, type = "upper", tl.pos = "td",
         method = "circle", tl.cex = 0.5, tl.col = 'black',
         order = "hclust", diag = FALSE)
```


```{r}
df_numeric %>% 
  select(40:50) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -clase_ternaria) %>% 
  rename(grupo = clase_ternaria) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```








### Excluyo columnas con muchos NAs

```{r}
var_excluir = nas %>% filter(nas > 30000) %>% .$var
df_numeric_small = df %>% dplyr::select(-(var_excluir))
```


Luego de excluir coumnas con NAs, excluyo filas con Nas

```{r}
df_numeric_small = df_numeric_small %>% 
  na.omit()
```












