---
title: "EDA"
author: "Sebastian Castillo"
date: '2022-06-25'
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(tidyr)
require("data.table")
require("randomForest")
require("ranger")
```

```{r}
setwd( "~/buckets/b1/" )  #cambiar por la carpeta local

#leo el dataset
dataset_grande  <- fread( "./datasets/paquete_premium.csv.gz", stringsAsFactors= TRUE)

#me quedo SOLO con los BAJA+2
dataset  <- copy( dataset_grande[  clase_ternaria =="BAJA+2"  & foto_mes>=202001  & foto_mes<=202011, ] )

#armo el dataset de los 12 meses antes de la muerte de los registros que analizo
dataset12  <- copy( dataset_grande[  numero_de_cliente %in%  dataset[ , unique(numero_de_cliente)]  ]  )

#asigno para cada registro cuantos meses faltan para morir
setorderv( dataset12, c("numero_de_cliente", "foto_mes"), c(1,-1) )
dataset12[  , pos := seq(.N) , numero_de_cliente ]

#me quedo solo con los 12 meses antes de morir
dataset12  <- dataset12[  pos <= 12 , ]
gc()


#quito los nulos para que se pueda ejecutar randomForest,  Dios que algoritmo prehistorico ...
dataset  <- na.roughfix( dataset )


#los campos que arbitrariamente decido considerar para el clustering
#por supuesto, se pueden cambiar
campos_buenos  <- c( "ctrx_quarter", "cpayroll_trx", "mcaja_ahorro", "mtarjeta_visa_consumo", "ctarjeta_visa_trx",
                     "mcuentas_saldo", "mrentabilidad_annual", "mprestamos_personales", "mactivos_margen", "mpayroll",
                     "Visa_mpagominimo", "Master_fechaalta", "cliente_edad", "chomebanking_trx", "Visa_msaldopesos",
                     "Visa_Fvencimiento", "mrentabilidad", "Visa_msaldototal", "Master_Fvencimiento", "mcuenta_corriente",
                     "Visa_mpagospesos", "Visa_fechaalta", "mcomisiones_mantenimiento", "Visa_mfinanciacion_limite",
                     "mtransferencias_recibidas", "cliente_antiguedad", "Visa_mconsumospesos", "Master_mfinanciacion_limite",
                     "mcaja_ahorro_dolares", "cproductos", "mcomisiones_otras", "thomebanking", "mcuenta_debitos_automaticos",
                     "mcomisiones", "Visa_cconsumos", "ccomisiones_otras", "Master_status", "mtransferencias_emitidas",
                     "mpagomiscuentas")



#Ahora, a esperar mucho con este algoritmo del pasado que NO correr en paralelo, patetico
modelo  <- randomForest( x= dataset[  , campos_buenos, with=FALSE ], 
                         y= NULL, 
                         ntree= 1000, #se puede aumentar a 10000
                         proximity= TRUE, 
                         oob.prox=  TRUE )

#genero los clusters jerarquicos
hclust.rf  <- hclust( as.dist ( 1.0 - modelo$proximity),  #distancia = 1.0 - proximidad
                      method= "ward.D2" )



#primero, creo la carpeta donde van los resultados
dir.create( "./exp/", showWarnings= FALSE )
dir.create( "./exp/ST7620", showWarnings= FALSE )
setwd( "~/buckets/b1/exp/ST7620" )


#imprimo un pdf con la forma del cluster jerarquico
pdf( "cluster_jerarquico.pdf" )
plot( hclust.rf )
dev.off()


#genero 7 clusters
h <- 20
distintos <- 0

while(  h>0  &  !( distintos >=3 & distintos <=4 ) )
{
  h <- h - 1 
  rf.cluster  <- cutree( hclust.rf, h)

  dataset[  , cluster2 := NULL ]
  dataset[  , cluster2 := rf.cluster ]

  distintos  <- nrow( dataset[  , .N,  cluster2 ] )
  cat( distintos, " " )
}

#en  dataset,  la columna  cluster2  tiene el numero de cluster
#sacar estadicas por cluster

dataset[  , .N,  cluster2 ]  #tamaño de los clusters

#grabo el dataset en el bucket, luego debe bajarse a la PC y analizarse
fwrite( dataset,
        file= "cluster_de_bajas.txt",
        sep= "\t" )


#ahora a mano veo los centroides de los 7 clusters
#esto hay que hacerlo para cada variable,
#  y ver cuales son las que mas diferencian a los clusters
#esta parte conviene hacerla desde la PC local, sobre  cluster_de_bajas.txt

dataset[  , mean(ctrx_quarter),  cluster2 ]  #media de la variable  ctrx_quarter
dataset[  , mean(mtarjeta_visa_consumo),  cluster2 ]
dataset[  , mean(mcuentas_saldo),  cluster2 ]
dataset[  , mean(chomebanking_trx),  cluster2 ]


#Finalmente grabo el archivo para  Juan Pablo Cadaveira
#agrego a dataset12 el cluster2  y lo grabo

dataset12[ dataset,
           on= "numero_de_cliente",
           cluster2 := i.cluster2 ]
```

```{r}
df_numeric = dataset12 %>% dplyr::select_if(is.numeric)
df_numeric = as_tibble(df_numeric)
var_target = dataset12 %>% dplyr::select(cluster2) #%>% 
  # mutate(cluster2 = case_when(
  #   cluster2 == "CONTINUA"  ~ 1,
  #   cluster2 == 'BAJA+1' ~ -1,
  #   cluster2 == 'BAJA+2' ~ -2))

```

```{r}
activo_boxplot = T
```

```{r, eval = activo_boxplot, fig.height=18, fig.width=18}
df_numeric %>% 
  #dplyr::select(var_elegidas) %>% 
  dplyr::select(1:20) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -cluster2) %>% 
  rename(grupo = cluster2) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```

```{r, eval = activo_boxplot, fig.height=18, fig.width=18}
df_numeric %>% 
  #dplyr::select(var_elegidas) %>% 
  dplyr::select(21:40) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -cluster2) %>% 
  rename(grupo = cluster2) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```

```{r, eval = activo_boxplot, fig.height=18, fig.width=18}
df_numeric %>% 
  #dplyr::select(var_elegidas) %>% 
  dplyr::select(41:60) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -cluster2) %>% 
  rename(grupo = cluster2) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```

```{r, eval = activo_boxplot, fig.height=18, fig.width=18}
df_numeric %>% 
  #dplyr::select(var_elegidas) %>% 
  dplyr::select(61:80) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -cluster2) %>% 
  rename(grupo = cluster2) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```

```{r, eval = activo_boxplot, fig.height=18, fig.width=18}
df_numeric %>% 
  #dplyr::select(var_elegidas) %>% 
  dplyr::select(81:100) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -cluster2) %>% 
  rename(grupo = cluster2) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```

```{r, eval = activo_boxplot, fig.height=18, fig.width=18}
df_numeric %>% 
  #dplyr::select(var_elegidas) %>% 
  dplyr::select(101:120) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -cluster2) %>% 
  rename(grupo = cluster2) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```


```{r, eval = activo_boxplot, fig.height=18, fig.width=18}
df_numeric %>% 
  #dplyr::select(var_elegidas) %>% 
  dplyr::select(121:140) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -cluster2) %>% 
  rename(grupo = cluster2) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```


```{r, eval = activo_boxplot, fig.height=18, fig.width=18}
df_numeric %>% 
  #dplyr::select(var_elegidas) %>% 
  dplyr::select(141:159) %>% 
  scale( center = TRUE, scale = TRUE) %>%  # Se escalan las variables, (x-median)/sd.
  bind_cols(var_target) %>%  
  pivot_longer(names_to = 'variables', values_to = 'cantidad', -cluster2) %>% 
  rename(grupo = cluster2) %>% 
  ggplot(aes(x=variables, y=cantidad, color=as.factor(grupo))) + 
  geom_boxplot() +
  #stat_summary(fun.y=mean, geom="point", color="red") +
  facet_wrap(~variables, scales = 'free') +
  labs(title = "Boxplot por grupo con variables escaladas")

```








