---
title: "Informe sobre MLOps"
author: "Claudio Sebastián Castillo"
date: "`r format(Sys.Date(), '%d de %B de %Y') `"
output:
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
linestretch: 1
params:
  AnalisisIntegrador: no
  primera_parte: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, comment=NA )
knitr::opts_chunk$set(fig.align = 'center')
options(DT.options = list(pageLength = 35, language = list(search = 'Filter:')))
source("Unidad0_repos_and_tools.R")
options(scipen = 999)
library(yaml)
library(DT)
library(forcats)
library(kableExtra)
```

```{r, params}
AI = params$AnalisisIntegrador
primera_parte = params$primera_parte

primera_parte = T
set.seed(1234)
```

# Modelos, gananciaBO, gananciaPublic

```{r,eval= (primera_parte | AI), fig.height=8, fig.width=14}
#----
setwd("~/R/labo/exp/8120HTa/")
filenames <- list.files(pattern="*.csv")
tbl <- do.call(rbind, lapply(filenames, function(x) cbind(fread(x, stringsAsFactors = FALSE), filename = x))) 
tbl = tbl %>% mutate(filename = str_replace_all(filename, "\\.csv", ''))
#----
tbl$gananciaPublic[str_detect(tbl$filename, "8120HTa")] = 21.74459
ganancia = tbl
#----
df = fread("~/R/labo/exp/8320HTa/8320HTa.csv") %>% 
  mutate(filename = "8320HTa", gananciaPublic = 18.79964)
ganancia = bind_rows(ganancia, df)
#------
# Entrenados en un mes
df1 = fread("~/R/labo/exp/8220HTi/8220HTi.csv") %>% 
  mutate(filename = "8220HTi", gananciaPublic = 21.38960)
df2 = fread("~/R/labo/exp/8220HTh/8220HTh.csv") %>% 
  mutate(filename = "8220HTh", gananciaPublic = 20.28962)
df3 = fread("~/R/labo/exp/8220HTg/8220HTg.csv") %>% 
  mutate(filename = "8220HTg", gananciaPublic = 21.26960)
df4 = fread("~/R/labo/exp/8220HTf/8220HTf.csv") %>% 
  mutate(filename = "8220HTf", gananciaPublic = 21.46459)
df5 = fread("~/R/labo/exp/8220HTe/8220HTe.csv") %>% 
  mutate(filename = "8220HTe", gananciaPublic = 21.49459)
df6 = fread("~/R/labo/exp/8220HTd/8220HTd.csv") %>% 
  mutate(filename = "8220HTd", gananciaPublic = 19.97462)
ganancia = bind_rows(ganancia, df1, df2, df3, df4, df5, df6)
#-------
# Entrenando con 
df = fread("~/R/labo/exp/8000HTa/8000HTa.csv") %>% 
  mutate(filename = "8000HTa", gananciaPublic = 19.43963)
ganancia = bind_rows(ganancia, df)
# Entrenando -------
df = fread("~/R/labo/exp/8121HTa/8121HTa.csv") %>% 
  mutate(filename = "8121HTa", gananciaPublic = 17.86466)
ganancia = bind_rows(ganancia, df)
# Entrenando -------
df = fread("~/R/labo/exp/8121HTc/8121HTc.csv") %>% 
  mutate(filename = "8121HTc", gananciaPublic = 19.35463)
ganancia = bind_rows(ganancia, df)
# Entrenando -------
df = fread("~/R/labo/exp/8121HTb/8121HTb.csv") %>% 
  mutate(filename = "8121HTb", gananciaPublic = 19.40963)
ganancia = bind_rows(ganancia, df)
# Entrenando -------
df = fread("~/R/labo/exp/8122HTa/8122HTa.csv") %>% 
  mutate(filename = "8122HTa", gananciaPublic = 20.56961)
ganancia = bind_rows(ganancia, df)
# Entrenando -------
df = fread("~/R/labo/exp/8122HTb/8122HTb.csv") %>% 
  mutate(filename = "8122HTb", gananciaPublic = 20.95960)
ganancia = bind_rows(ganancia, df)
# Entrenando -------
df = fread("~/R/labo/exp/8122HTc/8122HTc.csv") %>% 
  mutate(filename = "8122HTc", gananciaPublic = 21.41459)
ganancia = bind_rows(ganancia, df)
# Entrenando -------
df = fread("~/R/labo/exp/8122HTd/8122HTd.csv") %>% 
  mutate(filename = "8122HTd", gananciaPublic = 20.09462)
ganancia = bind_rows(ganancia, df)
# Entrenando -------
df = fread("~/R/labo/exp/8122HTe/8122HTe.csv") %>% 
  mutate(filename = "8122HTe", gananciaPublic = 19.66463)
ganancia = bind_rows(ganancia, df)
# Entrenando-------
df = fread("~/R/labo/exp/8122HTf/8122HTf.csv") %>% 
  mutate(filename = "8122HTf", gananciaPublic = 17.42967)
ganancia = bind_rows(ganancia, df)
# Entrenando-------
df = fread("~/R/labo/exp/8122HTg/8122HTg.csv") %>% 
  mutate(filename = "8122HTg", gananciaPublic = 20.57961)
ganancia = bind_rows(ganancia, df)
# Entrenando-------
df = fread("~/R/labo/exp/8122HTh/8122HTh.csv") %>% 
  mutate(filename = "8122HTh", gananciaPublic = 21.65959)
ganancia = bind_rows(ganancia, df)
# Entrenando-------
df = fread("~/R/labo/exp/8122HTi/8122HTi.csv") %>% 
  mutate(filename = "8122HTi", gananciaPublic = 18.95964)
ganancia = bind_rows(ganancia, df)
# Entrenando-------
df = fread("~/R/labo/exp/8122HTj/8122HTj.csv") %>% 
  mutate(filename = "8122HTj", gananciaPublic = 21.59959)
ganancia = bind_rows(ganancia, df)


# Hibridaciones
gan_8131 = ganancia %>% filter(str_detect(filename, "8121HTb|8122HTa")) %>% 
  group_by(filename) %>% 
  arrange(desc(ganancia)) %>%
  slice(1:10) %>%  ungroup() %>% 
  dplyr::select(ganancia) %>% 
  summarise_all(median) 

gan_8131d = ganancia %>% filter(str_detect(filename, "8122HTb|8122HTa" )) %>% 
  group_by(filename) %>% 
  arrange(desc(ganancia)) %>%
  slice(1:10) %>%  ungroup() %>% 
  dplyr::select(ganancia) %>% 
  summarise_all(median) 

gan_8131e = ganancia %>% filter(str_detect(filename, "8122HTc|8122HTd" )) %>% 
  group_by(filename) %>% 
  arrange(desc(ganancia)) %>%
  slice(1:10) %>%  ungroup() %>% 
  dplyr::select(ganancia) %>% 
  summarise_all(median) 

gan_8131f = ganancia %>% filter(str_detect(filename, "8122HTa|8122HTb|8122HTc|8122HTd|8122HTe|8122HTf" )) %>% 
  group_by(filename) %>% 
  arrange(desc(ganancia)) %>%
  slice(1:10) %>%  ungroup() %>% 
  dplyr::select(ganancia) %>% 
  summarise_all(median) 

gan_8131g = ganancia %>% filter(str_detect(filename, "8122HTa|8122HTc|8122HTe|8122HTg" )) %>% 
  group_by(filename) %>% 
  arrange(desc(ganancia)) %>%
  slice(1:10) %>%  ungroup() %>% 
  dplyr::select(ganancia) %>% 
  summarise_all(median) 


#8131HBa: [ "8220ZZi", "8121ZZb" ]  
#8131HBc: [ "8121ZZb", "8122ZZa" ]  
#8131HBd: [ "8122ZZb", "8122ZZa" ] 
#8131HBd: [ "8122ZZc", "8122ZZd" ]  
#8131HBf: [ "8122ZZa", "8122ZZb", "8122ZZc", "8122ZZd" , "8122ZZe", "8122ZZf" ]  
#8131HBg: [ "8122ZZa", "8122ZZc", "8122ZZe", "8122ZZg" ]  
#8131HBh: [ "8122ZZa", "8122ZZb", "8122ZZc", "8122ZZd" , "8122ZZe", "8122ZZf", "8122ZZg" , "8122ZZh", "8122ZZi", "8122ZZj", "8122ZZk",]  


temp = tribble(
  ~filename, ~ganancia, ~gananciaPublic,  
  "8131HBc_8121ZZb+8122ZZa", gan_8131$ganancia, 21.10960,  
  "8131HBd_8122ZZb+a", gan_8131d$ganancia, 21.44459, 
  "8131HBe_8122ZZc+d", gan_8131e$ganancia, 20.70, 
  "8131HBf_8122ZZa+b+c+d+e+f", gan_8131f$ganancia, 20.79961,
  "8131HBg_8122ZZa+c+e+g", gan_8131f$ganancia, 20.15462
  
)

#----------------------
ganancia_G = ganancia %>% 
  group_by(filename) %>% 
  arrange(desc(ganancia)) %>% 
  slice(1:15) %>% bind_rows(temp) %>%
  #ggplot(aes(x= reorder(filename, gananciaPublic) , y=ganancia/1000000, color = gananciaPublic)) +
  ggplot(aes(x= filename, y=ganancia/1000000, color = gananciaPublic)) + 
  geom_point() +
  scale_colour_viridis_c() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 14)) +
  labs(title = "Modelos según Ganancia en entrenamiento y Tablero Público",  
       x ="", y = "ganancia entrenamiento (millones)")

plotly::ggplotly(ganancia_G)
```

# Tabla para revisión de parámetros de experiementos corridos (parcial)

```{r, eval= (primera_parte | AI)}
setwd("~/R/labo/exp/")
filenames <- list.files(pattern="*.yml", recursive = T)
ymls <- do.call(rbind, lapply(filenames, function(x) cbind(read_yaml(x), filename = x))) 
param_groups = rownames(ymls)
ymls = as.tibble(ymls) %>% mutate(param_groups = param_groups)

df = ymls
df <- df %>%  filter(param_groups == "param") 

nexp = length(df$param_groups)
df_total = data.frame()

for(i in 1:nexp){
  
  tb = unlist(df$V1[i])
  tb = tibble(parametros =  names(tb), valores = as.character(tb))
  tb = tb %>% mutate(features_incluidos = !str_detect(valores, "FALSE|0"))
  tb = tb %>% 
    mutate(experimento = df$filename[i])
  
  df_total <- rbind(df_total, tb)

}

DT::datatable(df_total, class = "cell-border stripe", rownames = FALSE, filter ="top", 
              editable =TRUE, extension = "Buttons", fillContainer = FALSE,
              options = list(dom="Bfrtip",  buttons =c("copy", "csv", "excel", "pdf","print")))

```

# Tabla de revisión de Estrategia de Entrenamiento y sus respectivas ganancias

```{r}
ts <- df_total %>% 
  filter(str_detect(parametros, "desde|hasta|periodos|train.excluir"))

temp = ts %>% 
  filter(str_detect(parametros, "excluir")) %>% 
  group_by(experimento) %>% 
  summarise(excluir = str_c(valores, collapse = ", ")) %>% 
  mutate(excluir = str_remove_all(excluir, "20200"))

ts = ts %>% 
  filter(!str_detect(parametros, "excluir")) %>% 
  mutate(parametros = str_replace_all(parametros, " ", "_")) %>% 
  pivot_wider(names_from = parametros, values_from = valores) %>% 
  select(-c(features_incluidos, future.periodos, validate.rango.desde,  
            validate.rango.hasta, test.rango.desde, test.rango.hasta)) %>% 
  left_join(temp) %>% 
  mutate(filename = str_sub(experimento, 1,7)) %>% 
  mutate(filename = str_replace_all(filename, "TS", "HT")) %>% 
  left_join(ganancia %>% select(filename, ganancia, gananciaPublic) %>% 
              group_by(filename) %>% 
              filter(ganancia == max(ganancia))) %>% 
  select(filename, everything()) %>% 
  arrange(desc(ganancia))

ts %>% 
  kable() %>% 
  kable_classic(full_width = T, html_font = "Cambria") %>% 
  column_spec(10, color = "white",
              background = spec_color(ts$ganancia)) %>% 
  column_spec(11, color = "white",
              background = spec_color(ts$gananciaPublic))
```

# Revisión de Hiperparámetros

```{r}
ht <- df_total %>% 
  filter(str_detect(experimento, "HT")) %>% 
  filter(str_detect(parametros, "lightgbm|iterations")) %>% 
  mutate(valores = round(as.numeric(valores), digits = 2)) %>% 
  filter(!is.na(valores)) %>%# filter(valores != 0) %>% 
  mutate(parametros = str_remove_all(parametros, "lightgbm.")) %>% 
  select(-features_incluidos)

ht = ht %>% 
  pivot_wider(names_from = parametros, values_from = valores) %>% 
  mutate(filename = str_sub(experimento, 1,7)) %>% 
  left_join(ganancia %>% select(filename, ganancia, gananciaPublic) %>% 
              group_by(filename) %>% 
              filter(ganancia == max(ganancia))) %>% 
  select(filename,learning_rate1,learning_rate2,feature_fraction1,feature_fraction2,
         num_leaves1,num_leaves2,min_data_in_leaf1,min_data_in_leaf2,lambda_l1,lambda_l2,
         max_depth, BO.iterations, ganancia,gananciaPublic) %>% 
  arrange(desc(ganancia))

ht %>% 
  kable() %>% 
  kable_classic(full_width = T, html_font = "Cambria") %>% 
  column_spec(14, color = "white",
              background = spec_color(ht$ganancia)) %>% 
  column_spec(15, color = "white",
              background = spec_color(ht$gananciaPublic))

```

# Top 10 Modelos según mayor ganancia y sus respectivos hiperparámetros

```{r}
top10Model = ganancia %>% 
  arrange(desc(ganancia)) %>% 
  slice(1:20) %>% 
  select(experimento,  cols, rows, learning_rate, feature_fraction, num_leaves, min_data_in_leaf,
         num_iterations, estimulos, ganancia, gananciaPublic) %>% 
  arrange(desc(ganancia))

top10Model %>% 
  kable() %>% 
  kable_classic(full_width = T, html_font = "Cambria") %>% 
  column_spec(10, color = "white",
              background = spec_color(top10Model$ganancia)) %>% 
  column_spec(11, color = "white",
              background = spec_color(top10Model$gananciaPublic))

```

# Revisión de features

```{r, fig.height=8, fig.width=14}
setwd("~/R/labo/exp/impofiles")

filenames <- list.files(pattern="impo_*")

tbl <- do.call(rbind, 
               lapply(filenames, function(x) 
                 cbind(fread(x, stringsAsFactors = FALSE), filename = x)))

tbl = tbl %>% 
  group_by(filename) %>% 
  mutate(pos = row_number())

nfeatures = 35

features_G = tbl %>% 
  filter(!str_detect(Feature, "foto")) %>% 
  filter(pos < nfeatures) %>%
  ggplot(aes(Gain, fct_reorder(Feature, Gain))) +
  geom_col() +
  geom_col(aes(fill = filename)) +
  facet_wrap(~ filename, nrow = 1) +
  theme_minimal() +
  theme(
      legend.position = "none",
      plot.background = element_rect(fill = "#3e3d40", color = "#3e3d40"),
      strip.text.x = element_text(hjust = 0, color = "#dcbf35"),
      axis.title.x.top = element_text(color = "#dcbf35", hjust = 0),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.x = element_line(color = "#dcbf35"),
      panel.grid.minor.x = element_blank(),
      axis.text.y = element_text(colour = "white", size = 6),
      axis.title.y = element_blank(),
      axis.title.x = element_text(hjust = 0.5, colour = "grey"),
      axis.text.x = element_text(color = "#dcbf35"),
      plot.title = element_text(colour = "grey")) +
  labs(title = str_c("Top ", nfeatures," Features Gain by Experiment"))

plotly::ggplotly(features_G)

```

```{r, fig.height=8, fig.width=14}
features_G2 = tbl %>%
  filter(!str_detect(Feature, "foto")) %>%
  filter(pos < 35) %>%
  mutate(Gain = round(Gain, digits = 4)) %>%
  ggplot(aes(fill=Feature, y=Gain, x=filename)) +
  geom_point( stat="identity") +
  ggrepel::geom_label_repel(aes(label = Feature)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")

plotly::ggplotly(features_G2)

```
# Modelos por mes

```{r}
setwd("~/R/labo/datasets")

filenames <- list.files(pattern="bo_log_20*")

tbl <- do.call(rbind, 
               lapply(filenames, function(x) 
                 cbind(fread(x, stringsAsFactors = FALSE), filename = x)))

tbl %>%
  filter(!str_detect(filename, "10|11")) %>% 
  group_by(filename) %>% 
  arrange(desc(ganancia)) %>% 
  slice(1:15) %>% 
  ggplot(aes(fill=filename, x=filename, y=ganancia/1000000)) +
  geom_boxplot( ) +
  labs(title = "Entrenando modelos en datos mensuales y ganancia obtenidas en los 15 mejores")


```

<!-- # Modelo Denicolay1 -->

<!-- ```{r, eval= (primera_parte | AI), echo = T} -->
<!-- kdataset       <- "./datasets/paquete_premium_ext_721.csv.gz" -->
<!-- #donde entrenar -->
<!-- kfinal_mes_desde    <- 201912        #mes desde donde entreno -->
<!-- kfinal_mes_hasta    <- 202011        #mes hasta donde entreno, inclusive -->
<!-- kfinal_meses_malos  <- c( 202006 )   #meses a excluir del entrenamiento -->
<!-- #hiperparametros de LightGBM -->
<!-- #aqui copiar a mano lo menor de la Bayesian Optimization -->
<!-- # si es de IT y le gusta automatizar todo, no proteste, ya llegara con MLOps -->
<!-- kmax_bin           <-    31 -->
<!-- klearning_rate     <-     0.0131094708 -->
<!-- knum_iterations    <-   951 -->
<!-- knum_leaves        <-  1002 -->
<!-- kmin_data_in_leaf  <- 16918 -->
<!-- kfeature_fraction  <-     0.5609450635 -->

<!-- # 8120FEa_gustavo -->
<!-- # Contiene: lag1, tendencia6, avg6, minimo, delta1 -->
<!-- # 8120ZZ_gustavo -->
<!-- # Contiene: Semillero 50 -->


<!-- ``` -->
