---
title: "Informe Directora Comercial"
author: "Claudio Sebastián Castillo"
date: "`r format(Sys.Date(), '%d de %B de %Y') `"
output:
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
linestretch: 1
params:
  AnalisisIntegrador: no
  primera_parte: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, comment=NA )
knitr::opts_chunk$set(fig.align = 'center')
options(DT.options = list(pageLength = 35, language = list(search = 'Filter:')))
library(ggplot2)
library(gapminder)
library(gganimate)
library(data.table)
library(stringr)
library(directlabels)
library(dplyr)
library(GGally)
options(scipen = 999)

```


```{r}
## 'gapminder', 'gganimate', 
# https://www.datanovia.com/en/blog/gganimate-how-to-create-plots-with-beautiful-animation-in-r/

setwd( "~/buckets/b1/" )  #cambiar por la carpeta local

#leo el dataset
dataset_grande  <- fread( "./datasets/paquete_premium.csv.gz", stringsAsFactors= TRUE)

#me quedo SOLO con los BAJA+2
dataset  <- copy( dataset_grande[  clase_ternaria =="BAJA+2"  & 
                                     foto_mes>=202001  & foto_mes<=202011, ] )

#armo el dataset de los 12 meses antes de la muerte de los registros que analizo
dataset12  <- copy( dataset_grande[  numero_de_cliente %in%  dataset[ , unique(numero_de_cliente)]  ]  )

#asigno para cada registro cuantos meses faltan para morir
setorderv( dataset12, c("numero_de_cliente", "foto_mes"), c(1,-1) )
dataset12[  , pos := seq(.N) , numero_de_cliente ]
#me quedo solo con los 12 meses antes de morir
dataset12  <- dataset12[  pos <= 12 , ]

# data set continua
#me quedo SOLO con los BAJA+2
datasetC <- copy( dataset_grande[  clase_ternaria =="CONTINUA"  & 
                                     foto_mes>=202001  & foto_mes<=202011, ] )

#armo el dataset de los 12 meses antes de la muerte de los registros que analizo
dataset12C  <- copy( dataset_grande[  numero_de_cliente %in%  datasetC[ , unique(numero_de_cliente)]  ]  )

#asigno para cada registro cuantos meses faltan para morir
setorderv( dataset12C, c("numero_de_cliente", "foto_mes"), c(1,-1) )
dataset12C[  , pos := seq(.N) , numero_de_cliente ]
#me quedo solo con los 12 meses antes de morir
dataset12C  <- dataset12C[  pos <= 12 , ]
dataset12C <- dataset12C[ clase_ternaria == "CONTINUA", ]

dataset12$grupo = "grupo_baja"
dataset12C$grupo = "grupo_continua"
dataset = bind_rows(dataset12, dataset12C)

# Formateo fecha
df = dataset %>% 
  select(-c(clase_ternaria, numero_de_cliente)) %>% 
  mutate(date = as.Date(str_c(foto_mes, "01"), "%Y%m%d"))
```

# Señal temprana de renuncia de clientes (BAJA+2)

```{r}
# graficos temporales
# Señal temprana de baja
p = df %>% 
  filter(date > as.Date("2020-01-01")) %>% 
  group_by(date, grupo) %>% summarise_all(sum, na.rm = T) %>% 
  group_by(grupo) %>% mutate(ctrx_quarter_scaled = scale(ctrx_quarter)) %>% 
  ggplot(aes(y = ctrx_quarter_scaled, x=date, colour = grupo)) +
  geom_line() +
  theme(legend.position = "top", legend.title = element_blank()) +
  labs(title = "Señales de Baja: cantidad de transacciones",
       y = "Cantidad transacciones trimestrales", x = "") 
p + 
  geom_point() +
  transition_reveal(date)
```


# Propaga la señal a otras variables?

## Medianas

```{r}
# Propaga la señal a otras variables?
campos_buenos  <- c( "date", "grupo", "ctrx_quarter", "cpayroll_trx", "mcaja_ahorro", "mtarjeta_visa_consumo", "ctarjeta_visa_trx",
                     "mcuentas_saldo", "mrentabilidad_annual", "mprestamos_personales", "mactivos_margen", "mpayroll",
                     "Visa_mpagominimo", "Master_fechaalta", "cliente_edad", "chomebanking_trx", "Visa_msaldopesos",
                     "Visa_Fvencimiento", "mrentabilidad", "Visa_msaldototal", "Master_Fvencimiento", "mcuenta_corriente",
                     "Visa_mpagospesos", "Visa_fechaalta", "mcomisiones_mantenimiento", "Visa_mfinanciacion_limite",
                     "mtransferencias_recibidas", "cliente_antiguedad", "Visa_mconsumospesos", "Master_mfinanciacion_limite",
                     "mcaja_ahorro_dolares", "cproductos", "mcomisiones_otras", "thomebanking", "mcuenta_debitos_automaticos",
                     "mcomisiones", "Visa_cconsumos", "ccomisiones_otras", "Master_status", "mtransferencias_emitidas",
                     "mpagomiscuentas")
# promedio
df_allvars = df %>% 
  filter(date > as.Date("2020-01-01")) %>% 
  group_by(date, grupo) %>%
  #summarise_all(sum, na.rm = T) %>% 
  summarise_all(median, na.rm = T) %>% 
  select(campos_buenos) %>% 
  filter(date != as.Date("2020-06-01"))

temp = df_allvars %>% ungroup() %>% select(-c(date, grupo)) %>% mutate_all(scale) 

df_allvars = temp %>% 
  mutate(grupo = df_allvars$grupo, 
         date = df_allvars$date)

df_allvars = df_allvars %>% 
  tidyr::pivot_longer(names_to = "variables", values_to = "valores", -c(grupo, date)) 

df_allvars %>% 
  ggplot(aes(y = valores, x=date, colour = variables)) +
  geom_line() +
  theme(legend.position = "none") +
  labs(title = "Señales de Baja: cantidad de transacciones",
       y = "Cantidad transacciones trimestrales", x = "")  +
  facet_wrap(~grupo, scales = "free")
```

## Suma 

```{r}
# Suma sin escalamiento
df_allvars = df %>% 
  filter(date > as.Date("2020-01-01")) %>% 
  select(campos_buenos) %>% 
  group_by(date, grupo) %>%
  summarise_all(sum, na.rm = T) %>% 
  filter(date != as.Date("2020-06-01"))

# temp = df_allvars %>% ungroup() %>% select(-c(date, grupo)) %>% mutate_all(scale)
# df_allvars = temp %>%
#   mutate(grupo = df_allvars$grupo,
#          date = df_allvars$date)

df_allvars = df_allvars %>% 
  tidyr::pivot_longer(names_to = "variables", values_to = "valores", -c(grupo, date)) 

df_allvars %>% 
  #filter(date > as.Date("2020-07-01")) %>% 
  ggplot(aes(y = valores, x=date, colour = variables)) +
  geom_line() +
  geom_dl(aes(label = variables), method = list(dl.trans(x = x + 4), "first.points", cex = 0.8)) +
  scale_y_log10() +
  scale_x_date( date_labels = "%b-%Y") +
  theme(legend.position = "none") +
  labs(title = "Señales de Baja: otras variables",
       y = "Otros datos bancarios", x = "")  +
  facet_wrap(~grupo, scales = "free")
```

# Señal en el caso del consumo mediante Tarjetas de Crédito

```{r}
# Límite de financiacion de la tarjeta de crédito, expresado en pesos.
df_allvars = df %>% 
  filter(date > as.Date("2020-01-01")) %>% 
  select(campos_buenos) %>% 
  group_by(date, grupo) %>%
  summarise_all(sum, na.rm = T) %>% 
  filter(date != as.Date("2020-06-01"))

temp = df_allvars %>% ungroup() %>% select(-c(date, grupo)) %>% mutate_all(scale)

df_allvars = temp %>%
  mutate(grupo = df_allvars$grupo,
         date = df_allvars$date)

df_allvars = df_allvars %>% 
  tidyr::pivot_longer(names_to = "variables", values_to = "valores", -c(grupo, date)) 

df_allvars %>% 
  filter(str_detect(variables, "limite|consumo")) %>% 
  ggplot(aes(y = valores, x=date, colour = variables)) +
  geom_line() +
  geom_dl(aes(label = variables), method = list(dl.trans(x = x + 4), "first.points", cex = 0.8)) +
  scale_x_date( date_labels = "%b-%Y") +
  theme(legend.position = "none") +
  labs(title = "Señales de Baja: Consumo Visa-Master",
       y = "Otros datos bancarios", x = "")  +
  facet_wrap(~grupo, scales = "free")
```

# Otra Representación 

```{r}

# Plot
# Ver limite consumo y otra

df_allvars = df %>% 
  filter(date > as.Date("2020-01-01")) %>% 
  select(grupo, everything(), -foto_mes)
temp = df_allvars %>% select(1:40) %>% mutate(grupo= as.factor(grupo))
temp = temp %>% group_by(grupo) %>% slice(1:200)

ggparcoord(temp,
    columns = 20:25, groupColumn = 1, order = "anyClass",
    scale="uniminmax",
    showPoints = TRUE, 
    title = "No scaling",
    alphaLines = 0.3) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
 
```

